---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false

  roles:
    - db
