---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  sudo: true
  public_network

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: vagrant
  sudo: true
  public_network

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: vagrant
  sudo: true
  public_network

  roles:
    - db
