---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - common

# Configure and deploy database servers.
- hosts: dbservers
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: lbservers
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: monitoring
  user: root
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - base-apache
  - nagios
