---

- name: Demonstrate custom jinja2 filters
  hosts: all
  remote_user: vagrant
  sudo: true
  public_network
  
  tasks:
  - action: template src=templates/custom-filters.j2 dest=/tmp/custom-filters.txt
