---
- hosts: riak_cluster
  serial: 1
  remote_user: vagrant
  sudo: true
  
  pre_tasks:
  - name: make sure there are no transfers happening
    riak: wait_for_handoffs=600
  roles:
  - riak/common
