---
- hosts: riak_cluster
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - bootstrap/common

- hosts: Ubuntu
  gather_facts: no
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - bootstrap/ubuntu
  - riak/ubuntu
  - riak/common

- hosts: CentOS:RedHat
  gather_facts: no
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - bootstrap/redhat
  - riak/redhat
  - riak/common


