---
# This role contains common plays that will run on all nodes.

- name: install some SELinux things non-yum module
  raw: yum install -y libsemanage-python libselinux-python

- name: remove epel
  file: src=/etc/yum.repos.d/epel.repo state=absent

- name: Download EPEL
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: install some useful nagios plugins 
  yum: name={{ item }} state=present
  with_items:
   - nagios-plugins-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk
   - python-simplejson
   - ntp

- name: Configure ntp 
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
