---
# This role contains common plays that will run on all nodes.
- name: bootstrap python
  raw:  yum -y install python-simplejson libselinux-python

- name: download RPM for EPEL
  get_url: url=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/etc/epel-release-6-8.noarch.rpm mode=0440

- name: install the RPM
  shell: sudo rpm -ivh /etc/epel-release-6-8.noarch.rpm

- name: yum update all the things
  yum: name=* state=latest

- name: install some useful nagios plugins 
  yum: name={{ item }} state=present
  with_items:
   - nagios-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk

- name: Install ntp 
  yum: name=ntp state=present
  tags: ntp

- name: Configure ntp 
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
