---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
   - role: common

- hosts: mongo_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - role: mongod

- hosts: mongoc_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - role: mongoc

- hosts: mongos_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - role: mongos

- hosts: mongo_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  tasks:
  - include: roles/mongod/tasks/shards.yml 
