
- hosts: all
  
  roles:
      - role: common

- hosts: dns
  
  roles:
      - role: dns
- hosts: mongo_servers
  
  roles:
      - role: mongodb

- hosts: mq
  
  roles:
      - role: mq

- hosts: broker
  
  roles:
   - role: broker

- hosts: nodes
  
  roles:
   - role: nodes

- hosts: lvs
  
  roles:
   - role: lvs
