---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/ec2-us-west-2
  tasks:
  - name: Create the Instances for this vpc 
    ec2:
      region: "{{ ec2_region }}"
      keypair: "{{ ec2_keypair }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ ec2_image }}"
      wait: true
      instance_tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      count_tag: "{{ item.count_tag }}"
    register: ec2
    with_items: ec2_new_instances