---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/ec2
  tasks:
  - name: Create the Instances for this vpc 
    ec2:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ item.keypair }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ item.image }}"
      wait: true
      instance_tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      count_tag: "{{ item.count_tag }}"
    register: ec2
    with_items: ec2_new_instances