---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
# - hosts: tag_Name_demodfed
#   remote_user: "{{ uservar }}"
#   sudo: true
  
#   roles:
#   - common

# Configure and deploy database servers.
- hosts: tag_Demo_dbservers 
  remote_user: "{{ uservar }}"
  sudo: true
  roles:
  - common
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: tag_Demo_webservers
  remote_user: "{{ uservar }}"
  sudo: true
  roles:
  - common
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: tag_Demo_lbservers
  remote_user: "{{ uservar }}"
  sudo: true
  roles:
  - common
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: tag_Demo_monitoring
  remote_user: "{{ uservar }}"
  sudo: true
  roles:
  - common
  - base-apache
  - nagios
