---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  remote_user: root

  pre_tasks:

  - name: Raw bootstrap for python
    raw: yum -y install python libselinux-python
  
  roles:
  - common

# Configure and deploy database servers.
- hosts: tag_Name_dbservers
  remote_user: root
  
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: tag_Name_webservers
  remote_user: root
  
  roles:
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: tag_Name_lbservers
  remote_user: root
  
  roles:
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: tag_Name_monitoring
  remote_user: root
  
  roles:
  - base-apache
  - nagios
