---
# The main playbook to deploy the site

- hosts: hadoop_all
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
   - common

- hosts: zookeeper_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - { role: zookeeper_servers, when: ha_enabled }

- hosts: qjournal_servers
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - { role: qjournal_servers, when: ha_enabled }

- hosts: hadoop_master_primary
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - { role: hadoop_primary }

- hosts: hadoop_master_secondary
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - { role: hadoop_secondary, when: ha_enabled }

- hosts: hadoop_slaves
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false
  roles:
  - { role: hadoop_slaves }


