---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  public_network
  remote_user: vagrant
  sudo: true
  ask_sudo_pass: false

  roles:
    - common
    - mysql 
    - nginx
    - php-fpm
    - wordpress
