---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: standalone
  remote_user: vagrant
  sudo: true
  public_network

  roles:
    - common
    - mysql 
    - nginx
    - php-fpm
    - wordpress
