---
- name: Cent install and start apache
  hosts: tag_OS_cent
  remote_user: root
  sudo: true
  sudo_user: root

  tasks:

  - name: install httpd
    yum: name=httpd state=present

  - name: start httpd
    service: name=httpd state=running

- name: Ubuntu install and start apache
  hosts: tag_OS_ubuntu
  remote_user: ubuntu
  sudo: true
  sudo_user: root

  tasks:

  - name: install httpd
    apt: name=apache2 state=present

  - name: start httpd
    service: name=apache state=running