---
- name: set up a webserver
  hosts: tag_Demo_webservers
  remote_user: "{{ uservar }}"
  sudo: true
  sudo_user: root

  roles:
    - { role: webserver, when: "inventory_group == 'tag_OS_cent'" }
    - { role: webserver, when: "inventory_hostname == 'tag_OS_ubuntu'"}
